apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-connection-test
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: bitnami/mysql:latest
        command:
          - "bash"
          - "-c"
          - "mysql -hmysql -umyuser -pmyuserpwd -e 'SELECT NOW();'"
      restartPolicy: Never
