apiVersion: v1
kind: Pod
metadata:
  name: pod-init-sleep
spec:
  initContainers:
  - name: wait-before-start
    image: busybox
    command: ["sh", "-c", "echo 'Init démarre...' && sleep 10 && echo 'Init terminé'"]
  - name: wait-before-start
    image: busybox
    command: ["sh", "-c", "echo 'Init démarre supplémentaires...' && sleep 10 && echo 'Init supplémentaire terminé'"]
  containers:
  - name: main-container
    image: busybox
    command: ["sh", "-c", "echo 'Conteneur principal lancé après init' && sleep 3600"]
