apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: dev


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader-deleter
  namespace: dev
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "services", "deployments", "configmaps", "secrets", "jobs"]
  verbs: ["get", "list", "delete"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-sa-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: dev-sa
  namespace: dev
roleRef:
  kind: Role
  name: reader-deleter
  apiGroup: rbac.authorization.k8s.io


---


apiVersion: v1
kind: Pod
metadata:
  name: test-sa
  namespace: dev
spec:
  serviceAccountName: dev-sa
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]


## exemple d'utilisation
# kubectl exec -n dev -it test-sa -- sh
## Puis à l’intérieur du pod :
# kubectl get pods   # si kubectl est installé ou utilise l'API directement
